kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/multi-module-with-dependen
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
      # This expands to [space.s.]multi-module-with-dependen.<guid>.<region>.aksapp.io
      - $(spacePrefix)multi-module-with-dependen$(hostSuffix)
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
    container:
      sync:
      - "**/**"
      iterate:
        processesToKill: [java]
        buildCommands:
        - ["mvn","package","-Dmaven.test.skip=true","-Dcheckstyle.skip=true","-Dmaven.javadoc.skip=true"]